// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kncphogikrwsrehzhghc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuY3Bob2dpa3J3c3JlaHpoZ2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODQxNDEsImV4cCI6MjA2OTY2MDE0MX0.8IwcTI2K14FRa1THaOF1b9PjcOrdXYAsAZrgx_1Bw_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});