name: Import Builder UI
on:
  workflow_dispatch:
    inputs:
      builder_repo:
        description: 'Builder repo in owner/name format'
        required: true
        default: maxschanker/clink-builder
      builder_ref:
        description: 'Branch or tag to import'
        required: false
        default: main
      target_path:
        description: 'Where to place imported files'
        required: false
        default: vendor/builder-ui

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Lovable repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # safer than shell clone
      - name: Checkout Builder repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.builder_repo }}
          ref: ${{ inputs.builder_ref }}
          path: builder-src
          fetch-depth: 1

      - name: Prepare target folder
        run: |
          mkdir -p "${{ inputs.target_path }}"
          rm -rf "${{ inputs.target_path }}"/* || true

      - name: Copy UI artifacts from Builder
        run: |
          shopt -s dotglob || true
          if [ -d builder-src/client ]; then cp -R builder-src/client "${{ inputs.target_path }}/client"; fi
          if [ -d builder-src/public ]; then cp -R builder-src/public "${{ inputs.target_path }}/public"; fi
          if [ -f builder-src/tailwind.config.ts ]; then cp builder-src/tailwind.config.ts "${{ inputs.target_path }}/tailwind.config.builder.ts"; fi
          if [ -f builder-src/postcss.config.js ]; then cp builder-src/postcss.config.js "${{ inputs.target_path }}/postcss.config.builder.js"; fi
          if [ -f builder-src/components.json ]; then cp builder-src/components.json "${{ inputs.target_path }}/components.json"; fi
          if [ -f builder-src/LOVABLE_HANDOFF.md ]; then cp builder-src/LOVABLE_HANDOFF.md "${{ inputs.target_path }}/LOVABLE_HANDOFF.md"; fi
          echo "Imported files:"
          ls -la "${{ inputs.target_path }}" || true

      # ✅ Directly create a branch and push it (avoid PR action push issues)
      - name: Commit & push branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b chore/import-builder-ui
          git add "${{ inputs.target_path }}"
          # if nothing changed, don't fail
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0
          fi
          git commit -m "chore(ui): import Builder UI"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:chore/import-builder-ui
